:language: bash
:code: |
  curl -X POST https://www.scrooge.co.uk/oauth2/token\?\
    client_id\=your_client_id\&\
    client_secret\=your_client_secret\&\
    grant_type\=client_credentials\&\
    redirect_uri\=your_redirect_url\&\
    scope\=public
